// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYEmgtSPBlMj7HtmDl03VOM3uwLjGHgO0',
    appId: '1:975826656717:web:0a3fa29e69cfe79ce23884',
    messagingSenderId: '975826656717',
    projectId: 'finca-34db9',
    authDomain: 'finca-34db9.firebaseapp.com',
    storageBucket: 'finca-34db9.appspot.com',
    measurementId: 'G-79CV3C846J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhfZ1bNigLNHC7fY2waHFfNOCCMgNKOoc',
    appId: '1:975826656717:android:0f1969b4e9a9cdbae23884',
    messagingSenderId: '975826656717',
    projectId: 'finca-34db9',
    storageBucket: 'finca-34db9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB88-cWgfp4EDaO8Agx4M9T25bdjayVHEU',
    appId: '1:975826656717:ios:52775cb787158c93e23884',
    messagingSenderId: '975826656717',
    projectId: 'finca-34db9',
    storageBucket: 'finca-34db9.appspot.com',
    iosBundleId: 'pe.edu.upeu.asistenciaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB88-cWgfp4EDaO8Agx4M9T25bdjayVHEU',
    appId: '1:975826656717:ios:9e2ed1f1e562b0eee23884',
    messagingSenderId: '975826656717',
    projectId: 'finca-34db9',
    storageBucket: 'finca-34db9.appspot.com',
    iosBundleId: 'pe.edu.upeu.asistenciaApp.RunnerTests',
  );
}
